### ISSUE TITLE
Help needed! 

### ISSUE THREAD

**Issue by mstankovic** [kiwitcms/junit-plugin#160]
hello, im new in kiwi so currently evaluating this product..

Actually I run kiwi in docker and have it up and running. I manually added test cases, test plan containing those test cases and test run including those cases from the plan.

Also, I have selenium automation framework with automated cases representing test cases created in kiwi.

Also have integrated kiwi junit-plugin in my automation framework. 
I have ".tcms.conf" in my home dir with valid parameters.
able to create RpcClient connection and able to login.
Im trying to publish results im getting from executed selenium tests to execution on my test run on kiwi.

but not able to do that.

Do you support this kind of integration? If yes, can you please share some instructions for managing that.

Thanks in advice!

**Comment by atodorov** [comment]
You can start by asking your question on StackOverflow like instructed here https://kiwitcms.org/support/.

> but not able to do that.

And really post some error logs otherwise nobody will be able to help you.
