### ISSUE TITLE
java.lang.ClassCastException: class com.thetransactioncompany.jsonrpc2.JSONRPC2Error cannot be cast to class net.minidev.json.JSONObject (com.thetransactioncompany.jsonrpc2.JSONRPC2Error and net.minidev.json.JSONObject are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by zakariashahedbappa** [kiwitcms/junit-plugin#220]
```

            <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.kiwitcms.java/kiwitcms-junit-plugin -->
        <!-- https://mvnrepository.com/artifact/org.kiwitcms.java/kiwitcms-junit-plugin -->
        <dependency>
            <groupId>org.kiwitcms.java</groupId>
            <artifactId>kiwitcms-junit-plugin</artifactId>
            <version>9.0</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.4.0</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>
```

**Here is my dependency**

**Here is sample code**
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.kiwitcms.java.junit.KiwiTcmsExtension;

@ExtendWith(KiwiTcmsExtension.class)
public class sampleTest {
    @Test
    public void test1(){
        System.out.printf("test");
    }
    @Test
    public void test2(){
        System.out.printf("test");
    }

}

Getting error
**```
testtestInternal error: [('name', 'This field is required.'), ('classification', 'This field is required.')]

java.lang.ClassCastException: class com.thetransactioncompany.jsonrpc2.JSONRPC2Error cannot be cast to class net.minidev.json.JSONObject (com.thetransactioncompany.jsonrpc2.JSONRPC2Error and net.minidev.json.JSONObject are in unnamed module of loader 'app')

![image](https://user-images.githubusercontent.com/4609394/137985355-35cb7ae8-582b-4563-a41e-e9fe2fc433a5.png)
```**

**Comment by atodorov** [comment]
It looks like you the plugin can't figure out product name from your environment, see README for that.

It also looks like you haven't defined any product classifications in the database.
