### ISSUE TITLE
2 test runs created for the same build

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/junit-plugin#41]
With the new auto-discovery changes the plugin seems to create 2 test runs for the same build:
https://tcms.kiwitcms.org/runs/125/
https://tcms.kiwitcms.org/runs/126/

from what I can tell each test run references the results from a separate .java file, however all of these results must be in the same test run.

The fact that both files and test classes are named very similarly desn't help either.

Note: README probably needs to be updated with some instructions how to use the auto-discovery mechanism. 
Question: Is auto-discovery compatible with the `@ExtendWith` decorator?

**Comment by apetkova** [comment]
The PR addresses the multiple runs.
Re-question: Yes, auto-discovery can work with the declaration, it just makes it redundant
Re-README: It'd be nice if someone else can help with that; Here's the info that needs to be added re-auto loading (needs rephrasing, as this is taken from a blog post):
-----------------------------
Automatic, Global Registration
If you have an extension that you think needs to be registered with all tests in a suite, don’t bother adding it everywhere – that’s what the registration via service loader is there for. Simply let your extension JAR proclaim that it provides implementations of org.junit.jupiter.api.extension.Extension and Jupiter picks it up.
Automatic registration is turned off by default, so you first need to configure Jupiter to auto-detect extensions by setting junit.jupiter.extensions.autodetection.enabled to true. While your at it, consider requiring explicit activation for your extension with your own parameter (you can query it with the store’s getConfigurationParameter method). This way you can use your extension JAR without all global extensions being registered all the time.
---------------------
Jupiter = JUnit 5

**Comment by atodorov** [comment]
> The PR addresses the multiple runs.

I built the jar package locally so I can release to maven central. I had to defined product name/version/build and I got these 2 test runs:
https://tcms.kiwitcms.org/runs/181/
https://tcms.kiwitcms.org/runs/182/

Still not sure if this issue is fixed.

**Comment by atodorov** [comment]
Fixed in #47
